name: Measure canonical app size

on:
  # push:
  #   branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.2'
      - uses: nevkontakte/gopherjs-output-size@main
        with:
          name: jQuery TodoMVC
          repo: https://github.com/gopherjs/todomvc
          go-package: github.com/gopherjs/todomvc
          report: /tmp/report.json
      - uses: actions/upload-artifact@v2
        with:
          name: Report
          path: /tmp/report.json

